/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exameniilab_renatolizardo;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author Asus Pc
 */
public class PrincipalCompus extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalCompus
     */
    public PrincipalCompus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Computadoras = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfC_numserie = new javax.swing.JTextField();
        tfC_color = new javax.swing.JTextField();
        tfC_material = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbb_Rams = new javax.swing.JComboBox<>();
        Cbb_Discos = new javax.swing.JComboBox<>();
        Cbb_Baterias = new javax.swing.JComboBox<>();
        Cbb_teclado = new javax.swing.JComboBox<>();
        Cbb_Pantalla = new javax.swing.JComboBox<>();
        Cbb_Procesador = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jdc_Fecha = new com.toedter.calendar.JDateChooser();
        Jd_Tecnicos = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tft_nombre = new javax.swing.JTextField();
        tft_Edad = new javax.swing.JTextField();
        tft_Genero = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        Jd_simulacion = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Computadoras = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_tecnicos = new javax.swing.JList<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton16 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jd_Ram = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        tfMR_tiempo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfMR_tamano = new javax.swing.JTextField();
        tfMR_marca = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jd_DiscoDuro = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfDD_tiempo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfDD_Marca = new javax.swing.JTextField();
        tfDD_tamano = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jd_bateria = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfB_tiempo2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfB_Material = new javax.swing.JTextField();
        tfB_HorasBateria = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jd_teclado = new javax.swing.JDialog();
        tfT_Material = new javax.swing.JTextField();
        tfT_Color = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfT_tiempo3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jd_pantalla = new javax.swing.JDialog();
        tfPa_Tactil = new javax.swing.JTextField();
        tfPa_Tipo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfPa_tiempo4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jd_procesador = new javax.swing.JDialog();
        tfPr_Nucleos = new javax.swing.JTextField();
        tfPr_Velocidad = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tfPr_tiempo5 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JL_Listar = new javax.swing.JList<>();
        jButton15 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jd_Computadoras.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero de Serie");
        jd_Computadoras.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 146, -1, -1));

        jLabel2.setText("Ano");
        jd_Computadoras.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 207, -1, -1));

        jLabel3.setText("Color");
        jd_Computadoras.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 253, -1, -1));

        jLabel4.setText("Material");
        jd_Computadoras.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 312, -1, -1));
        jd_Computadoras.getContentPane().add(tfC_numserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 128, 113, -1));
        jd_Computadoras.getContentPane().add(tfC_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 253, 113, -1));
        jd_Computadoras.getContentPane().add(tfC_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 309, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Computadora");
        jd_Computadoras.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jToolBar1.setRollover(true);

        jButton1.setText("Agregar Ram");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Agregar Disco Duro");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Agregar Bateria");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton6.setText("Agregar Procesador");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton5.setText("Agregar Pantalla");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton4.setText("Agregar Teclado");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton4);

        jd_Computadoras.getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 20));

        jd_Computadoras.getContentPane().add(cbb_Rams, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 120, -1));

        jd_Computadoras.getContentPane().add(Cbb_Discos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 120, -1));

        jd_Computadoras.getContentPane().add(Cbb_Baterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 120, -1));

        jd_Computadoras.getContentPane().add(Cbb_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 120, -1));

        jd_Computadoras.getContentPane().add(Cbb_Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 120, -1));

        jd_Computadoras.getContentPane().add(Cbb_Procesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 120, -1));

        jLabel6.setText("Ram");
        jd_Computadoras.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jLabel7.setText("Disco Duro");
        jd_Computadoras.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jLabel8.setText("Bateria");
        jd_Computadoras.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        jLabel9.setText("Teclado");
        jd_Computadoras.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        jLabel10.setText("Pantalla");
        jd_Computadoras.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        jLabel11.setText("Procesador");
        jd_Computadoras.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 690, -1, -1));

        jButton8.setText("Agregar Computadora");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jd_Computadoras.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, -1, -1));
        jd_Computadoras.getContentPane().add(jdc_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, -1));

        jLabel12.setText("Nombre");

        jLabel13.setText("Edad");

        jLabel14.setText("Genero");

        jLabel15.setText("Tecnico");

        tft_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tft_EdadActionPerformed(evt);
            }
        });

        jButton7.setText("Agregar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Jd_TecnicosLayout = new javax.swing.GroupLayout(Jd_Tecnicos.getContentPane());
        Jd_Tecnicos.getContentPane().setLayout(Jd_TecnicosLayout);
        Jd_TecnicosLayout.setHorizontalGroup(
            Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jd_TecnicosLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jd_TecnicosLayout.createSequentialGroup()
                        .addGroup(Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(83, 83, 83)
                        .addGroup(Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(tft_nombre)
                            .addComponent(tft_Edad)
                            .addComponent(tft_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jd_TecnicosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton7)))
                .addGap(169, 169, 169))
        );
        Jd_TecnicosLayout.setVerticalGroup(
            Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jd_TecnicosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel15)
                .addGap(45, 45, 45)
                .addGroup(Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tft_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tft_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Jd_TecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tft_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButton7)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Jd_simulacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_Computadoras.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(JL_Computadoras);

        Jd_simulacion.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 190));

        JL_tecnicos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(JL_tecnicos);

        Jd_simulacion.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, 190));

        jLabel40.setText("Tecnicos");
        Jd_simulacion.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        jLabel41.setText("Computadoras");
        Jd_simulacion.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jProgressBar1.setStringPainted(true);
        Jd_simulacion.getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 469, 49));

        jButton16.setText("<------Ensamblar");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        Jd_simulacion.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 159, 37));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parte", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        Jd_simulacion.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 392, 306));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Recordar Seleccionar tanto a un tecnico \nComo a una computadora y luego presionar\nEl boton de ensamblar");
        jScrollPane5.setViewportView(jTextArea1);

        Jd_simulacion.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 290, 130));

        jLabel16.setText("Timpo de ensambaje");

        jLabel17.setText("Memoria RAM");

        jLabel18.setText("Tamano");

        jLabel19.setText("Marca");

        jButton14.setText("Agregar RAM");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_RamLayout = new javax.swing.GroupLayout(jd_Ram.getContentPane());
        jd_Ram.getContentPane().setLayout(jd_RamLayout);
        jd_RamLayout.setHorizontalGroup(
            jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_RamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(218, 218, 218))
            .addGroup(jd_RamLayout.createSequentialGroup()
                .addGroup(jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_RamLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(70, 70, 70)
                        .addGroup(jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMR_tiempo)
                            .addComponent(tfMR_tamano)
                            .addComponent(tfMR_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                    .addGroup(jd_RamLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton14)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jd_RamLayout.setVerticalGroup(
            jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RamLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addGap(48, 48, 48)
                .addGroup(jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfMR_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfMR_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_RamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfMR_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addGap(74, 74, 74))
        );

        jLabel20.setText("Tamano");

        jLabel21.setText("Timpo de ensambaje");

        jLabel22.setText("Marca");

        jLabel35.setText("DiscoDuro");

        jButton9.setText("Agregar Disco Duro");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_DiscoDuroLayout = new javax.swing.GroupLayout(jd_DiscoDuro.getContentPane());
        jd_DiscoDuro.getContentPane().setLayout(jd_DiscoDuroLayout);
        jd_DiscoDuroLayout.setHorizontalGroup(
            jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_DiscoDuroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(281, 281, 281))
            .addGroup(jd_DiscoDuroLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton9)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_DiscoDuroLayout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(jLabel22))
                    .addGap(70, 70, 70)
                    .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfDD_tiempo)
                        .addComponent(tfDD_tamano)
                        .addComponent(tfDD_Marca, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGap(0, 151, Short.MAX_VALUE)))
        );
        jd_DiscoDuroLayout.setVerticalGroup(
            jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DiscoDuroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(56, 56, 56))
            .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_DiscoDuroLayout.createSequentialGroup()
                    .addGap(0, 139, Short.MAX_VALUE)
                    .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(tfDD_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tfDD_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(jd_DiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(tfDD_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 139, Short.MAX_VALUE)))
        );

        jLabel23.setText("Horas");

        jLabel24.setText("Timpo de ensambaje");

        jLabel25.setText("Material");

        jButton10.setText("Agregar Bateria");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel36.setText("Bateria");

        javax.swing.GroupLayout jd_bateriaLayout = new javax.swing.GroupLayout(jd_bateria.getContentPane());
        jd_bateria.getContentPane().setLayout(jd_bateriaLayout);
        jd_bateriaLayout.setHorizontalGroup(
            jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_bateriaLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_bateriaLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_bateriaLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(231, 231, 231))))
            .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_bateriaLayout.createSequentialGroup()
                    .addGap(0, 97, Short.MAX_VALUE)
                    .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23)
                        .addComponent(jLabel25))
                    .addGap(70, 70, 70)
                    .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfB_tiempo2)
                        .addComponent(tfB_HorasBateria)
                        .addComponent(tfB_Material, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGap(0, 98, Short.MAX_VALUE)))
        );
        jd_bateriaLayout.setVerticalGroup(
            jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_bateriaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(38, 38, 38))
            .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_bateriaLayout.createSequentialGroup()
                    .addGap(0, 115, Short.MAX_VALUE)
                    .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(tfB_tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(tfB_HorasBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(jd_bateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(tfB_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 115, Short.MAX_VALUE)))
        );

        jLabel26.setText("Color");

        jLabel27.setText("Timpo de ensambaje");

        jLabel28.setText("Material");

        jButton11.setText("Teclado");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jLabel37.setText("Teclado");

        javax.swing.GroupLayout jd_tecladoLayout = new javax.swing.GroupLayout(jd_teclado.getContentPane());
        jd_teclado.getContentPane().setLayout(jd_tecladoLayout);
        jd_tecladoLayout.setHorizontalGroup(
            jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tecladoLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jButton11))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_tecladoLayout.createSequentialGroup()
                    .addGap(0, 115, Short.MAX_VALUE)
                    .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28)
                        .addComponent(jLabel26))
                    .addGap(70, 70, 70)
                    .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfT_tiempo3)
                        .addComponent(tfT_Material)
                        .addComponent(tfT_Color, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGap(0, 115, Short.MAX_VALUE)))
        );
        jd_tecladoLayout.setVerticalGroup(
            jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tecladoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(44, 44, 44))
            .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_tecladoLayout.createSequentialGroup()
                    .addGap(0, 139, Short.MAX_VALUE)
                    .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(tfT_tiempo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(tfT_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(jd_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(tfT_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 139, Short.MAX_VALUE)))
        );

        jLabel29.setText("Tipo");

        jLabel30.setText("Timpo de ensambaje");

        jLabel31.setText("Tactil");

        jLabel38.setText("Pantalla");

        jButton12.setText("Agregar Pantalla");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_pantallaLayout = new javax.swing.GroupLayout(jd_pantalla.getContentPane());
        jd_pantalla.getContentPane().setLayout(jd_pantallaLayout);
        jd_pantallaLayout.setHorizontalGroup(
            jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pantallaLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_pantallaLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(208, 208, 208))
            .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_pantallaLayout.createSequentialGroup()
                    .addGap(0, 93, Short.MAX_VALUE)
                    .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31)
                        .addComponent(jLabel29))
                    .addGap(70, 70, 70)
                    .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfPa_tiempo4)
                        .addComponent(tfPa_Tactil)
                        .addComponent(tfPa_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGap(0, 94, Short.MAX_VALUE)))
        );
        jd_pantallaLayout.setVerticalGroup(
            jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pantallaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(39, 39, 39))
            .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_pantallaLayout.createSequentialGroup()
                    .addGap(0, 105, Short.MAX_VALUE)
                    .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(tfPa_tiempo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(tfPa_Tactil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(tfPa_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 106, Short.MAX_VALUE)))
        );

        jLabel32.setText("Velocidad");

        jLabel33.setText("Timpo de ensambaje");

        jLabel34.setText("Numero de nucleos");

        jButton13.setText("Agregar Procesador");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jLabel39.setText("Procesador");

        javax.swing.GroupLayout jd_procesadorLayout = new javax.swing.GroupLayout(jd_procesador.getContentPane());
        jd_procesador.getContentPane().setLayout(jd_procesadorLayout);
        jd_procesadorLayout.setHorizontalGroup(
            jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_procesadorLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton13)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_procesadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(217, 217, 217))
            .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_procesadorLayout.createSequentialGroup()
                    .addGap(0, 90, Short.MAX_VALUE)
                    .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addComponent(jLabel34)
                        .addComponent(jLabel32))
                    .addGap(70, 70, 70)
                    .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfPr_tiempo5)
                        .addComponent(tfPr_Nucleos)
                        .addComponent(tfPr_Velocidad, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGap(0, 90, Short.MAX_VALUE)))
        );
        jd_procesadorLayout.setVerticalGroup(
            jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_procesadorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(49, 49, 49))
            .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_procesadorLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(tfPr_tiempo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(tfPr_Nucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(jd_procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(tfPr_Velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 124, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_Listar.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(JL_Listar);

        jButton15.setText("Actualizar");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jMenu1.setText("Agregar");

        jMenuItem1.setText("Agregar Computadora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agregar Tecnico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ensamblar");

        jMenuItem3.setText("Simular");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton15)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_Computadoras.setModal(true);
        jd_Computadoras.pack();
        jd_Computadoras.setLocationRelativeTo(this);
        jd_Computadoras.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Jd_Tecnicos.setModal(true);
        Jd_Tecnicos.pack();
        Jd_Tecnicos.setLocationRelativeTo(this);
        Jd_Tecnicos.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Jd_simulacion.setModal(true);
        Jd_simulacion.pack();
        Jd_simulacion.setLocationRelativeTo(this);
        Jd_simulacion.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      jd_Ram.setModal(true);
       jd_Ram.pack();
        jd_Ram.setLocationRelativeTo(this);
        jd_Ram.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_DiscoDuro.setModal(true);
        jd_DiscoDuro.pack();
        jd_DiscoDuro.setLocationRelativeTo(this);
        jd_DiscoDuro.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
             jd_bateria.setModal(true);
        jd_bateria.pack();
        jd_bateria.setLocationRelativeTo(this);
        jd_bateria.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        jd_procesador.setModal(true);
        jd_procesador.pack();
        jd_procesador.setLocationRelativeTo(this);
        jd_procesador.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        jd_pantalla.setModal(true);
        jd_pantalla.pack();
        jd_pantalla.setLocationRelativeTo(this);
        jd_pantalla.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jd_teclado.setModal(true);
        jd_teclado.pack();
        jd_teclado.setLocationRelativeTo(this);
        jd_teclado.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void tft_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tft_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tft_EdadActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // Boton de Para Agregar Tecnicos
 
        String nombre;
        int edad;
        String genero;
        int computadoras_ensabladas;
        
       nombre = tft_nombre.getText();
       edad = Integer.parseInt(tft_Edad.getText());
       genero = tft_Genero.getText();

       tecnico = new Tecnicos(nombre, edad, genero, 0);
       tecnicos.add(tecnico);
       
  
        
         DefaultListModel modelo = (DefaultListModel) JL_tecnicos.getModel();
        
        modelo.addElement(tecnicos);
        
        
       //JL_tecnicos.setModel(modelo);
       
       tft_nombre.setText("");
       tft_Edad.setText("");
       tft_Genero.setText("");

        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // Aqui Se agregar Las tarjetas RAM
        
        String tamano;
        String marca;
        int tiempo;
        
        tiempo = Integer.parseInt(tfMR_tiempo.getText());
        marca = tfMR_marca.getText();
        tamano = tfMR_tamano.getText();
        
        ram = new RAM(tamano, marca, tiempo);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbb_Rams.getModel();
        modelo.addElement(ram);
         cbb_Rams.setModel(modelo);
        
         
         tfMR_marca.setText("");
         tfMR_tamano.setText("");
         tfMR_marca.setText("");
        
        
        
        
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
    //Aqui Agregamos el disco Duro
        
        String tamano;
        String marca;
        int tiempo;

        tiempo = Integer.parseInt(tfDD_tiempo.getText());
        marca = tfDD_Marca.getText();
        tamano = tfDD_tamano.getText();

        disco = new DiscoDuro(tamano, marca, tiempo);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) Cbb_Discos.getModel();
        modelo.addElement(disco);
        Cbb_Discos.setModel(modelo);
        
        tfDD_Marca.setText("");
        tfDD_tamano.setText("");
        tfDD_tiempo.setText("");
        
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // Aqui Agregamos la Baterias
   
        String capacidad_horas;
        String material;
        int tiempo;

        tiempo = Integer.parseInt(tfB_tiempo2.getText());
        capacidad_horas = tfB_HorasBateria.getText();
        material = tfB_Material.getText();

        bateria = new bateria(capacidad_horas, material, tiempo);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) Cbb_Baterias.getModel();
        modelo.addElement(bateria);
        Cbb_Baterias.setModel(modelo);
        
        
        tfB_HorasBateria.setText("");
        tfB_Material.setText("");
        tfB_tiempo2.setText("");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // Aqui agregamos teclados
        
        String material;
        String color;
        int tiempo;

        tiempo = Integer.parseInt(tfT_tiempo3.getText());
        color = tfT_Color.getText();
        material = tfT_Material.getText();

        teclado = new Teclado(material, color, tiempo);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) Cbb_teclado.getModel();
        modelo.addElement(teclado);
        Cbb_teclado.setModel(modelo);
        
        tfT_Color.setText("");
        tfT_Material.setText("");
        tfT_tiempo3.setText("");
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Aqui se agregan Pantallas
        
        String tactil;
        String Tipo;
        int tiempo;

        tiempo = Integer.parseInt(tfPa_tiempo4.getText());
        tactil = tfPa_Tactil.getText();
        Tipo = tfPa_Tipo.getText();

        pantalla = new Pantalla(tactil, Tipo, tiempo);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) Cbb_Pantalla.getModel();
        modelo.addElement(pantalla);
        Cbb_Pantalla.setModel(modelo);
        
        tfPa_Tactil.setText("");
        tfPa_tiempo4.setText("");
        tfPa_Tipo.setText("");
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
         int num_nucleos;
    int velocidad;
        int tiempo;

        tiempo = Integer.parseInt(tfPr_tiempo5.getText());
        num_nucleos = Integer.parseInt(tfPr_Nucleos.getText());
        velocidad = Integer.parseInt(tfPr_Velocidad.getText());

        procesador = new Procesador(num_nucleos, velocidad, tiempo);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) Cbb_Procesador.getModel();
        modelo.addElement(procesador);
        Cbb_Procesador.setModel(modelo);
        
        tfPr_Nucleos.setText("");
        tfPr_Velocidad.setText("");
        tfPr_tiempo5.setText("");
        
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        
        //  Aqui agregamos Computadoras
        String num_serie;
        Date fecha;
        String color;
        String material;
        RAM ram;
        DiscoDuro disco_duro;
        bateria bateria;
        Teclado teclado;
        Pantalla pantalla;
        Procesador procesador;
        
        num_serie = tfC_numserie.getText();
        fecha = jdc_Fecha.getDate();
        color = tfC_color.getText();
        material = tfC_material.getText();
        ram = (RAM)cbb_Rams.getSelectedItem();
        disco_duro = (DiscoDuro)Cbb_Discos.getSelectedItem();
        bateria = (bateria)Cbb_Baterias.getSelectedItem();
        teclado = (Teclado)Cbb_teclado.getSelectedItem();
        pantalla = (Pantalla)Cbb_Pantalla.getSelectedItem();
        procesador = (Procesador)Cbb_Procesador.getSelectedItem();
 
        computadora = new Computadora(num_serie, fecha.toString(), color, material, ram, disco_duro, bateria, teclado, pantalla, procesador);
        computadoras.add(computadora);

        DefaultListModel modelo = (DefaultListModel) JL_Computadoras.getModel();

        modelo.addElement(computadoras);
        
     
        
        

        //JL_Computadoras.setModel(modelo);
        
        tfC_color.setText("");
        tfC_material.setText("");
        tfC_numserie.setText("");


    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        DefaultListModel modeloLISTA = (DefaultListModel)JL_Computadoras.getModel();
        DefaultListModel modeloLISTA2 = (DefaultListModel)JL_tecnicos.getModel();

       // Computadora computador = (Computadora)modeloLISTA.getElementAt(JL_Computadoras.getSelectedIndex());
        //Tecnicos tecnic = (Tecnicos) modeloLISTA2.getElementAt(JL_tecnicos.getSelectedIndex());
        
      try {
           // cargararchivo();
            Guardar(computadoras.get(JL_Computadoras.getSelectedIndex()));
            Guardar2(tecnicos.get(JL_tecnicos.getSelectedIndex()));
            
            //   MundoDisco m = (MundoDisco)modeloLISTA.getElementAt(Lista_Mundos.getSelectedIndex());
        } catch (IOException ex) {
            Logger.getLogger(PrincipalCompus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      
          ensam = new AdminEnsamblaje(this.jProgressBar1, computadoras.get(JL_Computadoras.getSelectedIndex()) , this.jTable1);
          ensam.start();
          
          
        
        modeloLISTA.remove(JL_Computadoras.getSelectedIndex());
        
        

         
        //m.getCriaturas().add((Criaturas)modeloLISTA2.getElementAt(Lista_Criaturas.getSelectedIndex()));
        //modeloLISTA2.remove(Lista_Criaturas.getSelectedIndex());
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        cargararchivo();
        System.out.println(computadoras);
        DefaultListModel modelo = (DefaultListModel) JL_Listar.getModel();

        for (int i = 0; i < computadoras.size(); i++) {

            modelo.addElement(computadoras.get(i));

        }
    }//GEN-LAST:event_jButton15MouseClicked

    
     public void Guardar(Computadora c) throws IOException{
             
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("./ArchivoExamenLab.txt", true);

            bw = new BufferedWriter(fw);

            bw.write(c.getNum_serie() + ";");
            bw.write(c.getFecha() + ";");
             bw.write(c.getColor() + ";");
            bw.write(c.getMaterial() + ";");
           
           
           

            bw.flush();
        } catch (Exception e) {

        }
        bw.close();
        fw.close();

    }
     
     
     
      public void cargararchivo(){
     
        
     
          //computadoras.add(new Computadora(sc.next(), sc.next(), sc.next(), sc.next(), new RAM() , new DiscoDuro() , new bateria() , new Teclado(), new Pantalla(), new Procesador()));
         File archivo = new File("./ArchivoExamenLab.txt"); 
          
        Scanner sc = null;
        computadoras = new ArrayList();
        if (archivo.exists()) {
            try {
                
                sc = new Scanner(archivo);
                sc.useDelimiter(";");
                while (sc.hasNext()) {
                    
                    
                    
                    computadoras.add(new Computadora(sc.next(), sc.next(),sc.next(),sc.next()));
                    
                
                }
            }
            
        catch(Exception e){
            
        }
        sc.close();
        }
        
        
         
    }
      
      
        public void Guardar2(Tecnicos t) throws IOException{
             
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("./ArchivoTecnicos.txt", true);

            bw = new BufferedWriter(fw);

            bw.write(t.nombre + ";");
            bw.write(t.edad + ";");
             bw.write(t.genero + ";");
            bw.write(t.computadoras_ensabladas + ";");
           
           
           

            bw.flush();
        } catch (Exception e) {

        }
        bw.close();
        fw.close();

    }
     
     
     
      public void cargararchivo2(){
     
        
     
          //computadoras.add(new Computadora(sc.next(), sc.next(), sc.next(), sc.next(), new RAM() , new DiscoDuro() , new bateria() , new Teclado(), new Pantalla(), new Procesador()));
         File archivo = new File("./ArchivoTecnicos.txt"); 
          
        Scanner sc = null;
        computadoras = new ArrayList();
        if (archivo.exists()) {
            try {
                
                sc = new Scanner(archivo);
                sc.useDelimiter(";");
                while (sc.hasNext()) {
                    
                    
                    
                    computadoras.add(new Computadora(sc.next(), sc.next(),sc.next(),sc.next()));
                    
                
                }
            }
            
        catch(Exception e){
            
        }
        sc.close();
        }
        
        
         
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCompus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCompus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCompus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCompus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCompus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbb_Baterias;
    private javax.swing.JComboBox<String> Cbb_Discos;
    private javax.swing.JComboBox<String> Cbb_Pantalla;
    private javax.swing.JComboBox<String> Cbb_Procesador;
    private javax.swing.JComboBox<String> Cbb_teclado;
    private javax.swing.JList<String> JL_Computadoras;
    private javax.swing.JList<String> JL_Listar;
    private javax.swing.JList<String> JL_tecnicos;
    private javax.swing.JDialog Jd_Tecnicos;
    private javax.swing.JDialog Jd_simulacion;
    private javax.swing.JComboBox<String> cbb_Rams;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_Computadoras;
    private javax.swing.JDialog jd_DiscoDuro;
    private javax.swing.JDialog jd_Ram;
    private javax.swing.JDialog jd_bateria;
    private javax.swing.JDialog jd_pantalla;
    private javax.swing.JDialog jd_procesador;
    private javax.swing.JDialog jd_teclado;
    private com.toedter.calendar.JDateChooser jdc_Fecha;
    private javax.swing.JTextField tfB_HorasBateria;
    private javax.swing.JTextField tfB_Material;
    private javax.swing.JTextField tfB_tiempo2;
    private javax.swing.JTextField tfC_color;
    private javax.swing.JTextField tfC_material;
    private javax.swing.JTextField tfC_numserie;
    private javax.swing.JTextField tfDD_Marca;
    private javax.swing.JTextField tfDD_tamano;
    private javax.swing.JTextField tfDD_tiempo;
    private javax.swing.JTextField tfMR_marca;
    private javax.swing.JTextField tfMR_tamano;
    private javax.swing.JTextField tfMR_tiempo;
    private javax.swing.JTextField tfPa_Tactil;
    private javax.swing.JTextField tfPa_Tipo;
    private javax.swing.JTextField tfPa_tiempo4;
    private javax.swing.JTextField tfPr_Nucleos;
    private javax.swing.JTextField tfPr_Velocidad;
    private javax.swing.JTextField tfPr_tiempo5;
    private javax.swing.JTextField tfT_Color;
    private javax.swing.JTextField tfT_Material;
    private javax.swing.JTextField tfT_tiempo3;
    private javax.swing.JTextField tft_Edad;
    private javax.swing.JTextField tft_Genero;
    private javax.swing.JTextField tft_nombre;
    // End of variables declaration//GEN-END:variables
Tecnicos tecnico;
Computadora computadora;

AdminEnsamblaje ensam;

RAM ram;
DiscoDuro disco;
bateria bateria;
Teclado teclado;
Pantalla pantalla;
Procesador procesador;


ArrayList<Tecnicos> tecnicos = new ArrayList();
ArrayList<Computadora> computadoras = new ArrayList();


/*
DefaultTableModel modelo = (DefaultTableModel)tabla1.getModel();
           modelo.removeRow(tabla1.getSelectedRow());
           tabla1.setModel(modelo); eliminar



Agregar
                            DefaultComboBoxModel modelo =  (DefaultComboBoxModel)cb_amigos.getModel();
                            modelo.addElement(x);
                            cb_amigos.setModel(modelo);

*/


}
